version: "3.8"
services:
  db:
    image: postgres:15
    container_name: board_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: board_db
      POSTGRES_USER: board_user
      POSTGRES_PASSWORD: board_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: board_redis
    restart: unless-stopped
    # ❗개발 편의상 포트 열어둠
    ports:
      - "6379:6379"
    # (선택) 비밀번호 쓰고 싶다면 아래 주석 해제
    # environment:
    #   REDIS_PASSWORD: devpass123
    # command: ["redis-server", "--requirepass", "devpass123"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
