version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: board_db
      POSTGRES_USER: board_user
      POSTGRES_PASSWORD: board_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U board_user -d board_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-db:
    image: redis:7-alpine
    container_name: redis_db
    restart: unless-stopped
    command: ["redis-server", "--requirepass"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-devredis} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
