version: '3.8'

services:
  board-api:
    image: reha0124/farmsystem-be:latest   # ← 팀 DockerHub 이미지로 변경
    container_name: board_api
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
