spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://RDS-ENDPOINT:5432/board_db}
    username: ${SPRING_DATASOURCE_USERNAME:board_user}
    password: ${SPRING_DATASOURCE_PASSWORD:board_pass}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis-db}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
